#Enable API and Dashboard
api:
  dashboard: true
  debug: true
# Entry points configuration
#
entryPoints:
  web:
    address: ":80"
    # redirect to https
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

  mariadb:
    address: ":3306"

serversTransport:
  insecureSkipVerify: true

# docker provider configuration
#
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

# certificate configuration for my resolvers and domain
#
certificatesResolvers:
  cloudflare:
    acme:
      email: savesaviourcomplex@proton.me
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"