version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
     - proxy
    restart: unless-stopped
    user: '1000'
    environment:
     - GF_SERVER_ROOT_URL=
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - /home/samuel/docker/utilities/grafana/data:/var/lib/grafana

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.local.getsamhome.com`)"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true