version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - proxy
    volumes:
      - /home/samuel/docker/media/jellyfin/config:/config
      - /home/samuel/docker/media/jellyfin/cache:/cache
      - /mnt/nfs/data/media:/media
      #- /path/to/media2:/media2:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
    # - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
   # extra_hosts:
    # - "host.docker.internal:host-gateway"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.local.getsamhome.com`)"
      - "traefik.http.routers.jellyfin-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=4533"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
