---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: homeserver-syncthing #optional
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - /home/samuel/docker/utilities/syncthing/config:/config
      - /mnt/nfs/data:/nfs/data
      - /mnt/db:/databases
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-secure.rule=Host(`syncthing.local.getsamhome.com`)"
      - "traefik.http.routers.syncthing-secure.entrypoints=websecure"
      - "traefik.http.routers.syncthing-secure.tls=true"
      - "traefik.http.routers.syncthing-secure.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true