---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
      - WEBUI_PORT=8280
    volumes:
      - /home/samuel/docker/downloaders/qbittorrent/config:/config
      - /mnt/nfs/data/torrents:/downloads
    ports:
      - 8280:8280
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.local.getsamhome.com`)"
      - "traefik.http.routers.qbittorrent-secure.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent-secure.tls=true"
      - "traefik.http.routers.qbittorrent-secure.service=qbittorrent"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8280"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true