---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Eastern
    volumes:
      - /home/samuel/docker/arr/sonarr/config:/config
      - /mnt/nfs/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.local.getsamhome.com`)"
      - "traefik.http.routers.sonarr-secure.entrypoints=websecure"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true